### ISSUE TITLE
take `privileged mode password ` at authentication

### ISSUE THREAD

**Issue by eslam-gomaa** [eslam-gomaa/Flexible-Network#48]
and login to the privileged mode **as part of authentication**

- That will let the users avoid the need to run `enable secret` command for example
  - Plus if the connection is reconnected, it will login to the privileged mode automatically

---

**To do**

- [x] support input for `privileged mode password` at authentication
- [x] make an option to enter the privileged-mode-password once the device is authenticated
  - #50 
  - #52 
- [x] Map with YAML

**Comment by eslam-gomaa** [comment]
Done #61 

**Examples**

```python
auth = task.authenticate(groups='works', user='orange', password='cisco', privileged_mode_password='cisco', port=22)
```

<br>

```yaml
Task:
  name: New Task
  log_format: markdown
  subTask:
    - name: Love forever
      vendor: cisco
      parallel: false
      authenticate:
        group: works
        port: 22
        username: orange
        password: cisco
        privileged_mode_password: cisco
        reconnect: false
      configBackup:
        comment: "Test backup"
        after_commands: false
        target: local
        skip:
          - 192.168.1.11
          - 192.168.1.12
      commands:
        - command: show ip int br
          tag: show1
          ask_for_confirmation: false
          exit_on_fail: false
          onlyOn:
            - 192.168.1.11            
        - command: |
            show version
          when:
            tag: show1
            operator: is
            exit_code: 0
```
