### ISSUE TITLE
Update YAML syntax for subtask credentials

### ISSUE THREAD

**Issue by eslam-gomaa** [eslam-gomaa/Flexible-Network#51]
**Example**

---

To do
- [x] password

 provide password directly
 ```yaml
password:
  value: ***
```
 Support reading password from ENV

```yaml
password:
  value_from_env:
    key: my_password
```

---

- [x] username

 provide username directly
 ```yaml
username:
  value: ****
```
 Support reading username from ENV

```yaml
username:
  value_from_env:
    key: my_username
```

---

- [x] privileged_mode_password

 provide password directly
 ```yaml
privileged_mode_password:
  value: ***
```
 Support reading password from ENV

```yaml
privileged_mode_password:
  value_from_env:
    key: my_password
```
