### ISSUE TITLE
support getting credentials from Vault and Cyberark in

### ISSUE THREAD

**Issue by eslam-gomaa** [eslam-gomaa/Flexible-Network#75]
**Example**

```yaml
password:
  value_from_vault:
    key:
```

```yaml
password:
  value_from_cyberark:
    key:
```

<br>

Let the methods available to be used in python scripts
